name 'onboard'
maintainer 'Embedded Now, Inc'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures onboard'
long_description 'Installs/Configures onboard'
version '0.1.0'
